development:
  secret_key_base: your_generated_secret_key
  key_id: your_generated_key_id
  key_secret: your_generated_secret_key

test:
  secret_key_base: your_generated_secret_key
  key_id: your_generated_key_id
  key_secret: your_generated_secret_key

production:
  secret_key_base: your_generated_secret_key
  key_id: your_generated_key_id
  key_secret: your_generated_secret_key
